Revert "[16.0][FIX] pinned requests_pkcs12 version due cryptography dependency"
This reverts commit 6e3f59489cf106289050d63ab29e7638d27d3cd8.

The fix started producing other dependency conflicts:

ERROR: Cannot install requests_pkcs12 because these package versions have conflicting dependencies.
The conflict is caused by:
    requests-pkcs12 1.22 depends on requests>=2.26.0
    The user requested (constraint) requests==2.25.1