[FIX] l10n_es_partner: Contact name may be empty
Odoo allows to have empty name on children contacts, provoking an error
when displaying the address with name_get:

  File "/opt/odoo/auto/addons/l10n_es_partner/models/res_partner.py", line 33, in _get_name
    return origin.replace(
TypeError: replace() argument 1 must be str, not bool

Let's cover that situation for avoiding the crash.

TT55861