[FIX] l10n_es_verifactu_oca: zeep responses without get
zeep return objects for the responses with no get method.

```
AttributeError: RespuestaRegFactuSistemaFacturacionType instance has no attribute 'get'
````

It wasn't detected in tests because of the mocked objects.